services:
  tstohls:
    image: ghcr.io/kronus09/tstohls:latest
    container_name: tstohls
    restart: unless-stopped
    ports:
      - "15140:15140"
    volumes:
      - ./data:/app/data
    environment:
      - TZ=Asia/Shanghai
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
